//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdiInvoicing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public decimal CHG_LOG_ID { get; set; }
        public Nullable<decimal> SRC_SYS_CHG_LOG_ID { get; set; }
        public Nullable<System.DateTime> SRC_SYS_TRANS_DT { get; set; }
        public string SRC_SYS_PROC_NM { get; set; }
        public string SRC_SYS_SESSION_NM { get; set; }
        public string SRC_SYS_USER_NM { get; set; }
        public string SRC_SYS_GRP_NM { get; set; }
        public string SRC_SYS_ACCT_NM { get; set; }
        public Nullable<decimal> SRC_SYS_SESSION_ID { get; set; }
        public string SRC_CD { get; set; }
        public string ACTION_CD { get; set; }
        public string CSI_TYPE_CD { get; set; }
        public decimal CUST_EDP { get; set; }
        public string CUST_NO { get; set; }
        public string NAME_ { get; set; }
        public string LNAME { get; set; }
        public string MI { get; set; }
        public string FNAME { get; set; }
        public string TITLE { get; set; }
        public string STREET { get; set; }
        public string CITY { get; set; }
        public string STATE_ { get; set; }
        public string ZIP { get; set; }
        public string ADDL_ADDR { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string GENDER_LANGUAGE { get; set; }
        public string CUST_WORTH { get; set; }
        public string CUST_TYPE { get; set; }
        public string CUST_STATUS { get; set; }
        public string STREET_ID { get; set; }
        public decimal CUST_EDP_ID { get; set; }
        public string CUST_CD { get; set; }
        public string CO_NM { get; set; }
        public string PERS_FAM_NM { get; set; }
        public string PERS_MID_NM { get; set; }
        public string PERS_GIV_NM { get; set; }
        public string PERS_TITLE_LGCY_CD { get; set; }
        public string PERS_SUFX_LGCY_CD { get; set; }
        public string ADDR_STREET_NM { get; set; }
        public string ADDR_CITY_NM { get; set; }
        public string ADDR_STATE_NM { get; set; }
        public string ADDR_POST_CD { get; set; }
        public string CTRY_LGCY_CD { get; set; }
        public string CUST_TYPE_LGCY_CD { get; set; }
        public string STREET_ID_CD { get; set; }
        public string CUST_ADDL_IND { get; set; }
        public string UPS_TYPE_LGCY_CD { get; set; }
        public string PERS_SEX_LGCY_CD { get; set; }
        public string LANG_LGCY_CD { get; set; }
        public string POSTALSOFT_POST_LGCY_CD { get; set; }
        public string CUST_STA_LGCY_CD { get; set; }
        public string CUST_ACTION_LGCY_CD { get; set; }
    }
}
