//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdiInvoicing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcomedateContextEntities : DbContext
    {
        public EcomedateContextEntities()
            : base("name=EcomedateContextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EDI_Document_ISA> EDI_Document_ISA { get; set; }
        public virtual DbSet<ImportedOrderPos> ImportedOrderPos { get; set; }
        public virtual DbSet<SearsOrderLine> SearsOrderLines { get; set; }
        public virtual DbSet<ShipTime> ShipTimes { get; set; }
        public virtual DbSet<EDI_Transaction_Log> EDI_Transaction_Log { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<FinanceTransaction> FinanceTransactions { get; set; }
        public virtual DbSet<OrderLine> OrderLines { get; set; }
        public virtual DbSet<OrderShipToXref> OrderShipToXrefs { get; set; }
        public virtual DbSet<ItemMaster> ItemMasters { get; set; }
        public virtual DbSet<OrderHeader> OrderHeaders { get; set; }
    }
}
