//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdiInvoicing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI_Document_ISA
    {
        public int EDI_Document_ISA_ID { get; set; }
        public string EDI_Document_ISA_Type { get; set; }
        public Nullable<System.DateTime> EDI_Document_ISA_Date { get; set; }
        public Nullable<int> EDI_TransactionControl_Start { get; set; }
        public Nullable<int> EDI_TransactionControl_End { get; set; }
    }
}
