//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceTransaction
    {
        public decimal CHG_LOG_ID { get; set; }
        public Nullable<decimal> SRC_SYS_CHG_LOG_ID { get; set; }
        public Nullable<System.DateTime> SRC_SYS_TRANS_DT { get; set; }
        public string SRC_SYS_PROC_NM { get; set; }
        public string SRC_SYS_SESSION_NM { get; set; }
        public string SRC_SYS_USER_NM { get; set; }
        public string SRC_SYS_GRP_NM { get; set; }
        public string SRC_SYS_ACCT_NM { get; set; }
        public Nullable<decimal> SRC_SYS_SESSION_ID { get; set; }
        public string SRC_CD { get; set; }
        public string ACTION_CD { get; set; }
        public string CSI_TYPE_CD { get; set; }
        public decimal CUST_EDP { get; set; }
        public string FULL_ORDER_NO { get; set; }
        public string COMPANY { get; set; }
        public string DIVISION { get; set; }
        public string DEPARTMENT { get; set; }
        public string DATE_ { get; set; }
        public string POSTED_DATE { get; set; }
        public Nullable<decimal> CONTROL_1 { get; set; }
        public Nullable<decimal> AMOUNTS_1 { get; set; }
        public Nullable<decimal> AMOUNTS_2 { get; set; }
        public Nullable<decimal> AMOUNTS_3 { get; set; }
        public Nullable<decimal> AMOUNTS_4 { get; set; }
        public Nullable<decimal> AMOUNTS_5 { get; set; }
        public Nullable<decimal> AMOUNTS_6 { get; set; }
        public string BIG_STATUS { get; set; }
        public Nullable<decimal> COUNTRY_CMP { get; set; }
        public decimal SLOTID { get; set; }
        public string SALES_ORD_NR { get; set; }
        public decimal CUST_EDP_ID { get; set; }
        public string CO_CD { get; set; }
        public string DIV_CD { get; set; }
        public string DEPT_CD { get; set; }
        public System.DateTime FIN_TRANS_DT { get; set; }
        public System.DateTime FIN_TRANS_POSTED_DT { get; set; }
        public decimal RTN_CONTROL_NR { get; set; }
        public decimal POST_CONTROL_NR { get; set; }
        public string FIN_TRANS_STA_LGCY_CD { get; set; }
        public string FIN_TRANS_MEMO_LGCY_CD { get; set; }
        public string FIN_TRANS_LGCY_CD { get; set; }
        public string CTRY_LGCY_CD { get; set; }
        public string ANTICIP_CHRG_IND { get; set; }
        public string DOCUMENT_NR { get; set; }
        public string TRANSMITTAL_NR { get; set; }
        public Nullable<decimal> EDP_NO_ID { get; set; }
    }
}
