//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemMaster()
        {
            this.OrderLine = new HashSet<OrderLine>();
        }
    
        public decimal CHG_LOG_ID { get; set; }
        public Nullable<decimal> SRC_SYS_CHG_LOG_ID { get; set; }
        public Nullable<System.DateTime> SRC_SYS_TRANS_DT { get; set; }
        public string SRC_SYS_PROC_NM { get; set; }
        public string SRC_SYS_SESSION_NM { get; set; }
        public string SRC_SYS_USER_NM { get; set; }
        public string SRC_SYS_GRP_NM { get; set; }
        public string SRC_SYS_ACCT_NM { get; set; }
        public Nullable<decimal> SRC_SYS_SESSION_ID { get; set; }
        public string SRC_CD { get; set; }
        public string ACTION_CD { get; set; }
        public string CSI_TYPE_CD { get; set; }
        public decimal EDP_NO { get; set; }
        public Nullable<decimal> ALT_EDP_NO { get; set; }
        public Nullable<decimal> ACTUAL_EDP_NO { get; set; }
        public Nullable<decimal> UNIT_FACTOR { get; set; }
        public string DESCRIPTION { get; set; }
        public string ITEM_NO { get; set; }
        public Nullable<decimal> REORDER_POINT { get; set; }
        public string WAREHOUSE_LOCS_1 { get; set; }
        public string WAREHOUSE_LOCS_2 { get; set; }
        public string WAREHOUSE_LOCS_3 { get; set; }
        public string WAREHOUSE_LOCS_4 { get; set; }
        public string WAREHOUSE_LOCS_5 { get; set; }
        public string WAREHOUSE_LOCS_6 { get; set; }
        public string WAREHOUSE_LOCS_7 { get; set; }
        public string WAREHOUSE_LOCS_8 { get; set; }
        public string WAREHOUSE_LOCS_9 { get; set; }
        public string WAREHOUSE_LOCS_10 { get; set; }
        public string CLASS_ { get; set; }
        public string DIVISION { get; set; }
        public string DEPARTMENT { get; set; }
        public string SEASON { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string MIN_ORDER_QTY { get; set; }
        public string MAX_ORDER_QTY { get; set; }
        public string POST_HAND { get; set; }
        public string WEIGHT { get; set; }
        public string LENGTH_ { get; set; }
        public string WIDTH { get; set; }
        public string DEPTH_ { get; set; }
        public string SHIP_METHOD { get; set; }
        public string FIRST_DATE_ADV { get; set; }
        public string LAST_DATE_ADV { get; set; }
        public string STOP_SHOP_DATE { get; set; }
        public Nullable<decimal> AVAILABLE_INV { get; set; }
        public Nullable<decimal> CURRENT_BO { get; set; }
        public Nullable<decimal> BO_FO_NEED { get; set; }
        public Nullable<decimal> BO_FO_SAVE { get; set; }
        public Nullable<decimal> AVAILABLE_ALL { get; set; }
        public Nullable<decimal> RESERVES_1 { get; set; }
        public Nullable<decimal> RESERVES_2 { get; set; }
        public Nullable<decimal> RESERVES_3 { get; set; }
        public Nullable<decimal> RESERVES_4 { get; set; }
        public Nullable<decimal> RESERVES_5 { get; set; }
        public Nullable<decimal> PO_NUMBERS_1 { get; set; }
        public Nullable<decimal> PO_NUMBERS_2 { get; set; }
        public Nullable<decimal> PO_NUMBERS_3 { get; set; }
        public Nullable<decimal> PO_NUMBERS_4 { get; set; }
        public Nullable<decimal> PO_NUMBERS_5 { get; set; }
        public string EXPECTED_DATE_1 { get; set; }
        public string EXPECTED_DATE_2 { get; set; }
        public string EXPECTED_DATE_3 { get; set; }
        public string EXPECTED_DATE_4 { get; set; }
        public string EXPECTED_DATE_5 { get; set; }
        public Nullable<decimal> NEXT_QTY_1 { get; set; }
        public Nullable<decimal> NEXT_QTY_2 { get; set; }
        public Nullable<decimal> NEXT_QTY_3 { get; set; }
        public Nullable<decimal> NEXT_QTY_4 { get; set; }
        public Nullable<decimal> NEXT_QTY_5 { get; set; }
        public Nullable<decimal> IN_TRANSIT_QTY_1 { get; set; }
        public Nullable<decimal> IN_TRANSIT_QTY_2 { get; set; }
        public Nullable<decimal> IN_TRANSIT_QTY_3 { get; set; }
        public Nullable<decimal> INV_COST_1 { get; set; }
        public Nullable<decimal> INV_COST_2 { get; set; }
        public Nullable<decimal> INV_COST_3 { get; set; }
        public Nullable<decimal> REMOTE_QTY_1 { get; set; }
        public Nullable<decimal> REMOTE_QTY_2 { get; set; }
        public Nullable<decimal> REMOTE_QTY_3 { get; set; }
        public string VENDOR_NO { get; set; }
        public string FLAGS { get; set; }
        public string VARIABLE_LEVEL { get; set; }
        public string VARIABLE_LEVEL2 { get; set; }
        public string CYCLE_WEEKS { get; set; }
        public string NEXT_COUNT_DATE { get; set; }
        public string COUNT_DATE { get; set; }
        public string TICKET_NO { get; set; }
        public string CONTINUITY_PROG { get; set; }
        public string STYLE_ { get; set; }
        public string FILLER_96 { get; set; }
        public string TITLE { get; set; }
        public Nullable<decimal> BOX_EDP_NO { get; set; }
        public Nullable<decimal> PACK_EDP_NO { get; set; }
        public string ADDITIONAL_DATA { get; set; }
        public string USER_ID { get; set; }
        public string DATE_ { get; set; }
        public string TIME_ { get; set; }
        public string STATUS { get; set; }
        public decimal EDP_NO_ID { get; set; }
        public string LONG_NM { get; set; }
        public string ITM_CD { get; set; }
        public Nullable<decimal> REORD_POINT_QTY { get; set; }
        public string CA_TARR_CLS_LGCY_CD { get; set; }
        public string DIV_CD { get; set; }
        public string SEASON_LGCY_CD { get; set; }
        public string MAJ_CAT_LGCY_CD { get; set; }
        public string SUB_MAJ_CAT_LGCY_CD { get; set; }
        public string MIN_CAT_LGCY_CD { get; set; }
        public string SUB_MIN_CAT_LGCY_CD { get; set; }
        public Nullable<decimal> SELL_PRICE_AMT { get; set; }
        public Nullable<decimal> MIN_ORD_QTY { get; set; }
        public Nullable<decimal> MAX_ORD_QTY { get; set; }
        public Nullable<decimal> ADDL_PH_AMT { get; set; }
        public Nullable<decimal> WGHT { get; set; }
        public Nullable<decimal> LNGTH { get; set; }
        public Nullable<decimal> WDTH { get; set; }
        public Nullable<decimal> DPTH { get; set; }
        public string SHIP_METH_LGCY_CD { get; set; }
        public Nullable<System.DateTime> FIRST_ADV_DT { get; set; }
        public Nullable<System.DateTime> STOP_SHOP_DT { get; set; }
        public Nullable<decimal> AVL_INV_QTY { get; set; }
        public Nullable<decimal> CURR_BO_QTY { get; set; }
        public Nullable<decimal> BO_FO_NEED_QTY { get; set; }
        public Nullable<decimal> BO_FO_SAVE_QTY { get; set; }
        public Nullable<decimal> AVL_ALL_QTY { get; set; }
        public Nullable<decimal> ITM_UNIT_COST_AMT { get; set; }
        public string CUSTOM_REQD_CD { get; set; }
        public string CUSTOM_LGCY_CD { get; set; }
        public string SERIAL_NO_REQD_IND { get; set; }
        public string TAX_EXEMPT_LGCY_CD { get; set; }
        public string HAZ_LGCY_CD { get; set; }
        public string AUTO_PURCH_IND { get; set; }
        public string ASSOC_ITM_LGCY_CD { get; set; }
        public Nullable<decimal> WARR_DAYS { get; set; }
        public string AUTO_CHECK_OFF_LGCY_CD { get; set; }
        public string ALT_PH_LGCY_CD { get; set; }
        public string DISC_LGCY_CD { get; set; }
        public string HANGFLAT_LGCY_CD { get; set; }
        public string BOX_LGCY_CD { get; set; }
        public string CO_CD { get; set; }
        public string ROY_CD { get; set; }
        public string PH_EXCL_IND { get; set; }
        public string RESTRICT_SHIP_LGCY_CD { get; set; }
        public string AUTO_HOLD_LGCY_CD { get; set; }
        public string TO_BE_BUILT_IND { get; set; }
        public string DROP_SHIP_LGCY_CD { get; set; }
        public string RP_FACT_LGCY_CD { get; set; }
        public string SPEC_UPS_4_CLS_IND { get; set; }
        public string STYMTX_PRICE_SW_IND { get; set; }
        public string EXPLOSION_SW_LGCY_CD { get; set; }
        public Nullable<decimal> UNIT_CNT_QTY { get; set; }
        public Nullable<decimal> MIN_SALE_PRICE_AMT { get; set; }
        public string STY_MOD_SW_LGCY_CD { get; set; }
        public string FTC_IND { get; set; }
        public Nullable<decimal> DIM_WGHT { get; set; }
        public string PH_CAT_LGCY_CD { get; set; }
        public string ACK_LTR_LGCY_CD { get; set; }
        public Nullable<decimal> SHRINK_PCT { get; set; }
        public string VEND_STY_CHGD_LGCY_CD { get; set; }
        public string EXCL_FRM_DISC_LGCY_CD { get; set; }
        public string WEB_EXCL_IND { get; set; }
        public string WEB_STYLE_EXCL_IND { get; set; }
        public Nullable<decimal> CYCLE_WEEKS_AMT { get; set; }
        public Nullable<System.DateTime> NEXT_CNT_DT { get; set; }
        public Nullable<System.DateTime> COUNT_DT { get; set; }
        public string FO_DT_LGCY_CD { get; set; }
        public string CTRY_LGCY_CD { get; set; }
        public string CASE_KIT_LGCY_CD { get; set; }
        public string SUPPRESS_CMPNT_IND { get; set; }
        public string PKMS_SHIP_ALONE_IND { get; set; }
        public string CTN_TYPE_LGCY_CD { get; set; }
        public string PRT_LBL_LGCY_CD { get; set; }
        public string OVERSIZE_LGCY_CD { get; set; }
        public string ADDL_HDLG_LGCY_CD { get; set; }
        public string STY_CD { get; set; }
        public string GW_TYPE_LGCY_CD { get; set; }
        public string ROY_8_CD { get; set; }
        public string TAX_LGCY_CD { get; set; }
        public string CONS_LGCY_CD { get; set; }
        public string LEASE_LGCY_CD { get; set; }
        public string QTY_TRK_IND { get; set; }
        public Nullable<decimal> MAX_AVAIL_TO_SELL_QTY { get; set; }
        public Nullable<decimal> TOT_SOLD_QTY { get; set; }
        public Nullable<System.DateTime> START_SHIP_DT { get; set; }
        public string C1_CANCEL_IND { get; set; }
        public string BAG_SLAP_LGCY_CD { get; set; }
        public string UPSELL_ST_LGCY_CD { get; set; }
        public string ITM_CLS_LGCY_CD { get; set; }
        public Nullable<decimal> INWH_INV_QTY { get; set; }
        public Nullable<decimal> INWH_VAL_AMT { get; set; }
        public string CHAIN_CD { get; set; }
        public string RETDISP_LGCY_CD { get; set; }
        public string GW_LGCY_CD { get; set; }
        public Nullable<System.DateTime> CRE_DT { get; set; }
        public Nullable<System.DateTime> REORD_DT { get; set; }
        public string BUYER_CD { get; set; }
        public string NO_DEM_IND { get; set; }
        public string POS_DEPT_LGCY_CD { get; set; }
        public Nullable<decimal> CUB_VOL { get; set; }
        public string MIN_BOX_LGCY_CD { get; set; }
        public string INCR_BOX_LGCY_CD { get; set; }
        public string BOX_TYPE_LGCY_CD { get; set; }
        public string EXP_LGCY_CD { get; set; }
        public string INS_LGCY_CD { get; set; }
        public string MAT_REL_LGCY_CD { get; set; }
        public string MERCH_LGCY_CD { get; set; }
        public string CO_SHARE_IND { get; set; }
        public string STY_PRC_LVL_CD { get; set; }
        public string USER_CD { get; set; }
        public Nullable<System.DateTime> MOD_DT { get; set; }
        public string ITM_STA_LGCY_CD { get; set; }
        public string DEL_CONF_TYPE_LGCY_CD { get; set; }
        public string WMS_PA_LGCY_CD { get; set; }
        public string SHOP_FILT_LGCY_CD { get; set; }
        public string STR_VAL_CARD_IND { get; set; }
        public string CTN_SZ_EXCL_IND { get; set; }
        public string NON_BOX_CD { get; set; }
        public string STYLE_STAT_LGCY_CD { get; set; }
        public string WEIGH_AT_POS_CD { get; set; }
        public string VIRTUAL_CARD_CD { get; set; }
        public string ASM_IN_WHSE_CD { get; set; }
        public string AFFILIATE_CD { get; set; }
        public string INSTALL_TABLE_LGCY_CD { get; set; }
        public string SO_1_PERIOD_LGCY_CD { get; set; }
        public Nullable<decimal> SO_1_INTERVAL { get; set; }
        public string SO_2_PERIOD_LGCY_CD { get; set; }
        public Nullable<decimal> SO_2_INTERVAL { get; set; }
        public string CC_BILL_UP_FRONT_CD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLine { get; set; }
    }
}
