//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public decimal CHG_LOG_ID { get; set; }
        public Nullable<decimal> SRC_SYS_CHG_LOG_ID { get; set; }
        public Nullable<System.DateTime> SRC_SYS_TRANS_DT { get; set; }
        public string SRC_SYS_PROC_NM { get; set; }
        public string SRC_SYS_SESSION_NM { get; set; }
        public string SRC_SYS_USER_NM { get; set; }
        public string SRC_SYS_GRP_NM { get; set; }
        public string SRC_SYS_ACCT_NM { get; set; }
        public Nullable<decimal> SRC_SYS_SESSION_ID { get; set; }
        public string SRC_CD { get; set; }
        public string ACTION_CD { get; set; }
        public string CSI_TYPE_CD { get; set; }
        public decimal FIFONO { get; set; }
        public decimal SLOTID { get; set; }
        public string SALES_ORD_NR { get; set; }
        public decimal SALES_ORD_LN_NR { get; set; }
        public string SALES_ORD_SHIP_TO_NR { get; set; }
        public Nullable<decimal> EDP_NO_ID { get; set; }
        public Nullable<decimal> ASSOC_LN_NR { get; set; }
        public Nullable<decimal> ITM_QTY { get; set; }
        public Nullable<decimal> EXT_PRC_AMT { get; set; }
        public Nullable<decimal> EXT_COST_AMT { get; set; }
        public Nullable<decimal> INV_HARD_ALLOC_QTY { get; set; }
        public string REL_ALLOC_IND { get; set; }
        public Nullable<decimal> ORIG_PRC_AMT { get; set; }
        public string ORD_ITM_HP_LGCY_CD { get; set; }
        public string ORD_ITM_TYPE_LGCY_CD { get; set; }
        public string ORIG_ORD_ITM_HP_LGCY_CD { get; set; }
        public string ORD_ITM_POR_LGCY_CD { get; set; }
        public string ORD_ITM_STA_LGCY_CD { get; set; }
        public string SALES_ORD_SHIP_NR { get; set; }
        public Nullable<System.DateTime> SHIP_DT { get; set; }
        public string SHIP_METH_SHIP_LGCY_CD { get; set; }
        public string PICK_LOT_CD { get; set; }
        public string ORD_SUB_STA_LGCY_CD { get; set; }
        public Nullable<System.DateTime> SHIP_CONF_DT { get; set; }
        public string SHIP_METH_LGCY_CD { get; set; }
        public Nullable<decimal> TAX_RATE_PCT { get; set; }
        public string TAX_JUR_CD { get; set; }
        public Nullable<decimal> PICKED_ITM_CNT { get; set; }
        public Nullable<decimal> UNPICKED_ITM_CNT { get; set; }
        public Nullable<decimal> SHIPMENT_CNT { get; set; }
        public string SKIP_NDAY_IND { get; set; }
    
        public virtual ItemMaster ItemMasters { get; set; }
    }
}
