//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdiInvoicing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHeader
    {
        public decimal CHG_LOG_ID { get; set; }
        public Nullable<decimal> SRC_SYS_CHG_LOG_ID { get; set; }
        public Nullable<System.DateTime> SRC_SYS_TRANS_DT { get; set; }
        public string SRC_SYS_PROC_NM { get; set; }
        public string SRC_SYS_SESSION_NM { get; set; }
        public string SRC_SYS_USER_NM { get; set; }
        public string SRC_SYS_GRP_NM { get; set; }
        public string SRC_SYS_ACCT_NM { get; set; }
        public Nullable<decimal> SRC_SYS_SESSION_ID { get; set; }
        public string SRC_CD { get; set; }
        public string ACTION_CD { get; set; }
        public string CSI_TYPE_CD { get; set; }
        public Nullable<decimal> CUST_EDP { get; set; }
        public string FULL_ORDER_NO { get; set; }
        public string COMPANY { get; set; }
        public string DIVISION { get; set; }
        public string SOURCE_ { get; set; }
        public string MAIL_DATE { get; set; }
        public string ENTRY_DATE { get; set; }
        public string ENTRY_TIME { get; set; }
        public string REMIT_DATE { get; set; }
        public string ENTRY_OPER { get; set; }
        public string PAY_METHOD { get; set; }
        public Nullable<decimal> PRODUCT_DOLLARS { get; set; }
        public Nullable<decimal> ITEM_COUNT { get; set; }
        public string FLAGS { get; set; }
        public string DISCOUNT_CODES { get; set; }
        public Nullable<decimal> SHIP_ITEM_COUNT { get; set; }
        public Nullable<decimal> SHIPMENT_COUNT { get; set; }
        public string LAST_SHIPMENT { get; set; }
        public Nullable<decimal> AUDIT_DATES_1 { get; set; }
        public Nullable<decimal> AUDIT_DATES_2 { get; set; }
        public Nullable<decimal> AUDIT_DATES_3 { get; set; }
        public Nullable<decimal> AUDIT_DATES_4 { get; set; }
        public Nullable<decimal> AUDIT_DATES_5 { get; set; }
        public Nullable<decimal> AUDIT_DATES_6 { get; set; }
        public Nullable<decimal> AUDIT_DATES_7 { get; set; }
        public Nullable<decimal> AUDIT_DATES_8 { get; set; }
        public Nullable<decimal> AUDIT_DATES_9 { get; set; }
        public Nullable<decimal> AUDIT_DATES_10 { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> COUNTRY_CMP { get; set; }
        public string FLAGS_2 { get; set; }
        public Nullable<decimal> CUST_EDP_ID { get; set; }
        public decimal FIFONO { get; set; }
        public decimal SLOTID { get; set; }
        public string SALES_ORD_NR { get; set; }
        public string CO_CD { get; set; }
        public string DIV_CD { get; set; }
        public string OFFER_CD { get; set; }
        public string USE_CD { get; set; }
        public Nullable<System.DateTime> SALES_ORD_MAIL_DT { get; set; }
        public Nullable<System.DateTime> SALES_ORD_ENTRY_DT { get; set; }
        public string USER_CD { get; set; }
        public string ENTRY_SYS_LGCY_CD { get; set; }
        public string FOP_TYPE_LGCY_CD { get; set; }
        public Nullable<decimal> TOT_BEFORE_DISC_AMT { get; set; }
        public Nullable<decimal> NR_OF_LN_ITM { get; set; }
        public string ORD_HTC_LGCY_CD { get; set; }
        public string ORD_NBO_LGCY_CD { get; set; }
        public string TAX_EXMPT_IND { get; set; }
        public string ORD_TYPE_LGCY_CD { get; set; }
        public string FIRST_TIME_IND { get; set; }
        public string INQ_CONV_IND { get; set; }
        public string PRI_IND { get; set; }
        public string BC_IND { get; set; }
        public Nullable<decimal> SHIP_TO_CNT { get; set; }
        public string DROP_SHIP_IND { get; set; }
        public string ORD_PH_TYPE_LGCY_CD { get; set; }
        public string ORD_PH_SUR_LGCY_CD { get; set; }
        public string SERIAL_NR_IND { get; set; }
        public string FOP_CAT_LGCY_CD { get; set; }
        public string BILL_WHEN_COMPLETE_IND { get; set; }
        public string CC_UP_FRONT_IND { get; set; }
        public string AUTO_ORD_IND { get; set; }
        public string AVAIL_CRED_LGCY_CD { get; set; }
        public string MULTI_OFFER_IND { get; set; }
        public string PAYER_IND { get; set; }
        public string PROD_EXEMPT_IND { get; set; }
        public string DEDICATED_SM_IND { get; set; }
        public string QUICK_SHIP_TYPE_LGCY_CD { get; set; }
        public string SAT_DELIV_IND { get; set; }
        public string SIGN_REL_IND { get; set; }
        public string SUPPR_PREDEF_COMM_IND { get; set; }
        public string LINE_ITEM_INSTALL_BILL_IND { get; set; }
        public string DISC_OFFER_LGCY_CD { get; set; }
        public Nullable<decimal> DISC_AMT { get; set; }
        public string INSUR_REF_IND { get; set; }
        public string BILL_WHEN_WH_COMPL_IND { get; set; }
        public Nullable<decimal> CONV_RATE { get; set; }
        public string PRESHIP_INSTALL_IND { get; set; }
        public string PACK_SLIP_COMM_IND { get; set; }
        public string BACK_ORD_IND { get; set; }
        public string COUP_IND { get; set; }
        public string DISC_LGCY_CD { get; set; }
        public string SECOND_DISC_LGCY_CD { get; set; }
        public Nullable<decimal> SHIP_ITEM_CNT { get; set; }
        public Nullable<decimal> SHIP_CNT { get; set; }
        public Nullable<System.DateTime> ORD_LAST_SHIP_DT { get; set; }
        public string PH_UP_FRONT_EXCL_IND { get; set; }
        public string INSUR_EXEMPT_IND { get; set; }
        public string ORD_STA_LGCY_CD { get; set; }
        public string CTRY_LGCY_CD { get; set; }
        public string RFND_WHEN_CANCL_IND { get; set; }
        public string GIFT_CARD_IND { get; set; }
        public string POS_ORD_TYPE_LGCY_CD { get; set; }
        public string POS_SHIP_FROM_LGCY_CD { get; set; }
        public string POS_REG_LGCY_CD { get; set; }
        public string DEL_CONF_TYPE_LGCY_CD { get; set; }
        public string REGISTER_CD { get; set; }
        public string MARKET_LGCY_CD { get; set; }
        public string UP_FRONT_OA_LGCY_CD { get; set; }
        public string INSTALL_TABLE_LGCY_CD { get; set; }
        public string STANDING_ORDER_CD { get; set; }
    }
}
