//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdiInvoicing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearsOrderLine
    {
        public int ID { get; set; }
        public string PONumber { get; set; }
        public string PODate { get; set; }
        public string ItemID { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string CustomerOrderNumber { get; set; }
        public Nullable<int> SettingID { get; set; }
        public string LineID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ImportPoNumber { get; set; }
        public Nullable<System.DateTime> ImportTimeStamp { get; set; }
        public string MappedItemId { get; set; }
        public string ShipMethod { get; set; }
        public Nullable<bool> AmazonPrime { get; set; }
        public string ShipmentId { get; set; }
        public string MerchantTrackingNumber { get; set; }
        public Nullable<int> LineQuantity { get; set; }
        public Nullable<bool> IsBusinessAddress { get; set; }
    }
}
