//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipTime
    {
        public int ID { get; set; }
        public string OrderNumber { get; set; }
        public string ProductNumber { get; set; }
        public Nullable<int> CarrierID { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<System.DateTime> ArriveDate { get; set; }
        public string TrackingNumber { get; set; }
        public string PONumber { get; set; }
        public string SourceCode { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<bool> KitComponent { get; set; }
        public string DWSku { get; set; }
        public Nullable<System.DateTime> ShipConfirmDate { get; set; }
        public string PayMethod { get; set; }
        public string OrderNumberOnly { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> AssocLineNo { get; set; }
        public string SearsPoNumber { get; set; }
    }
}
