//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_OrderImportSettings
    {
        public int SettingId { get; set; }
        public string SourceName { get; set; }
        public string FileLocation { get; set; }
        public string ImportType { get; set; }
        public string Delimiter { get; set; }
        public Nullable<int> StartAtLine { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> NumberOfImportCols { get; set; }
        public Nullable<bool> CalculateTax { get; set; }
        public string DefaultSourceCode { get; set; }
        public string PaymentSource { get; set; }
        public string DefaultPaymentType { get; set; }
        public string DefaultOrderType { get; set; }
        public string RemoteTransferType { get; set; }
        public string RemoteURL { get; set; }
        public Nullable<int> RemotePort { get; set; }
        public string RemoteUserName { get; set; }
        public string RemotePassword { get; set; }
        public string RemoteNotificationEmail { get; set; }
        public string RemoteFilePath { get; set; }
        public string RemoteFileNamePattern { get; set; }
        public Nullable<bool> RemoteDeleteAfterDownload { get; set; }
        public Nullable<bool> RemoteIsPassiveMode { get; set; }
        public Nullable<int> BillToFirstNameCol { get; set; }
        public Nullable<int> BillToLastNameCol { get; set; }
        public Nullable<int> BillToCompanyCol { get; set; }
        public Nullable<int> BillToAddress1Col { get; set; }
        public Nullable<int> BillToAddress2Col { get; set; }
        public Nullable<int> BillToCityCol { get; set; }
        public Nullable<int> BillToStateCol { get; set; }
        public Nullable<int> BillToZipCol { get; set; }
        public Nullable<int> BillToDayPhoneCol { get; set; }
        public Nullable<int> BillToNightPhoneCol { get; set; }
        public Nullable<int> BillToEmailCol { get; set; }
        public Nullable<int> ShipToFirstNameCol { get; set; }
        public Nullable<int> ShipToLastNameCol { get; set; }
        public Nullable<int> ShipToCompanyCol { get; set; }
        public Nullable<int> ShipToAddress1Col { get; set; }
        public Nullable<int> ShipToAddress2Col { get; set; }
        public Nullable<int> ShipToCityCol { get; set; }
        public Nullable<int> ShipToStateCol { get; set; }
        public Nullable<int> ShipToZipCol { get; set; }
        public Nullable<int> ShipToDayPhoneCol { get; set; }
        public Nullable<int> ShipToNightPhoneCol { get; set; }
        public Nullable<int> ShipToEmailCol { get; set; }
        public Nullable<int> ItemSkuCol { get; set; }
        public Nullable<int> ItemDescriptionCol { get; set; }
        public Nullable<int> ItemQtyCol { get; set; }
        public Nullable<int> ItemPriceCol { get; set; }
        public Nullable<int> ItemTaxCol { get; set; }
        public Nullable<int> ItemDiscountCol { get; set; }
        public Nullable<int> ItemShipPriceCol { get; set; }
        public Nullable<int> ItemShipTaxCol { get; set; }
        public Nullable<int> ItemShipDiscountCol { get; set; }
        public Nullable<int> ItemShipMethodCol { get; set; }
        public Nullable<int> DiscountCode1Col { get; set; }
        public Nullable<int> DiscountCode2Col { get; set; }
        public Nullable<int> GiftMessageLine1Col { get; set; }
        public Nullable<int> GiftMessageLine2Col { get; set; }
        public Nullable<int> ShipCommentLine1Col { get; set; }
        public Nullable<int> ShipCommentLine2Col { get; set; }
        public Nullable<int> CCardTypeCol { get; set; }
        public Nullable<int> CCardNumberCol { get; set; }
        public Nullable<int> CCardExpYYCol { get; set; }
        public Nullable<int> CCardExpMMCol { get; set; }
        public Nullable<int> CCardCSVCol { get; set; }
        public Nullable<int> CCardAuthCodeCol { get; set; }
        public Nullable<int> CCardResponseCodeCol { get; set; }
        public Nullable<int> PaymentBirthdayCol { get; set; }
        public Nullable<int> PamentPromoCodeCol { get; set; }
        public Nullable<int> PaymentDivisionCol { get; set; }
        public Nullable<int> PaymentPONoCol { get; set; }
        public Nullable<int> PaymentTypeCol { get; set; }
        public Nullable<int> OrderDateCol { get; set; }
        public Nullable<int> VendorOrderIDCol { get; set; }
        public Nullable<int> LDOrderIDCol { get; set; }
        public Nullable<int> ActionCustHoldCol { get; set; }
        public Nullable<int> ActionReviewHoldCol { get; set; }
        public Nullable<int> ActionExpediteCol { get; set; }
        public string OrderPrefix { get; set; }
        public Nullable<int> NextOrderNumber { get; set; }
        public string DefaultBillToFirstName { get; set; }
        public string DefaultBillToLastName { get; set; }
        public string DefaultBillToCompany { get; set; }
        public string DefaultBillToAddress1 { get; set; }
        public string DefaultBillToAddress2 { get; set; }
        public string DefaultBillToCity { get; set; }
        public string DefaultBillToState { get; set; }
        public string DefaultBillToZip { get; set; }
        public string DefaultBillToDayPhone { get; set; }
        public string DefaultBillToNightPhone { get; set; }
        public string DefaultBillToEmail { get; set; }
        public bool UseDefaultBillTo { get; set; }
        public bool PriceIsTotalNotPerUnit { get; set; }
        public Nullable<int> ShipToPhoneCommentNightCol { get; set; }
        public Nullable<int> ShipToPhoneCommentDayCol { get; set; }
        public Nullable<int> BillToPhoneCommentNightCol { get; set; }
        public Nullable<int> BillToPhoneCommentDayCol { get; set; }
        public Nullable<int> SourceCodeCol { get; set; }
        public string XSLTFileLocation { get; set; }
        public Nullable<int> DefaultShipMethod { get; set; }
        public bool DoNotArchive { get; set; }
        public Nullable<int> PaymentSourceCol { get; set; }
        public bool PriceIsHidden { get; set; }
        public bool IsOverridablePrice { get; set; }
        public string ShipConfirmDir { get; set; }
        public Nullable<int> ShipConfirmDayCount { get; set; }
        public string RemoteShipConfirmDir { get; set; }
        public Nullable<System.DateTime> LastRunOrderImport { get; set; }
        public Nullable<System.DateTime> LastRunShipConfirm { get; set; }
        public Nullable<bool> IsCCardEncrypted { get; set; }
        public Nullable<bool> IsMerchantOrder { get; set; }
        public string DefaultCustomerEdpNo { get; set; }
        public Nullable<bool> UsePoForEcomSubmission { get; set; }
    }
}
